#30 Updated images, logo, LDAP configs
geosolutions-it/MapStore2-c126 pull request #35
Opened 2021-07-08 12:35 UTC by offtherailz

Updated 
 - Logo and header image
 - Social links
 - LDAP configuration, alinged with production

2021-07-08 12:40 UTC, offtherailz commented
When merged, you can publish https://github.com/geosolutions-it/MapStore2-c126/releases/tag/untagged-ac650eed3357dee1ef32 from master.

Waiting for confirmation about LDAP configurations to be working again.

2021-07-09 09:38 UTC, tdipisa requested changes
The HTML Title
should be updated to 

`<title>GeoDAS Newmont</title>`

In the following files:

- api.html
- embedded.html
- index.html

change already applied to client instance in PROD

2021-07-14 10:30 UTC, offtherailz commented on web/src/main/resources-filtered/WEB-INF/classes/geostore-spring-security.xml
> +                                <entry key="PEN_GIS_ADMIN_W_SGG" value="ROLE_ADMIN"/>
```suggestion
```

2021-08-04 14:42 UTC, tdipisa approved these changes

2021-08-04 14:42 UTC, merged